# Copyright 2019 Manna Harbour
# https://github.com/manna-harbour/miryoku

MIRYOKU_ALPHAS = QWERTY
MIRYOKU_TAP = QWERTY
MIRYOKU_EXTRA = COLEMAKDH
MIRYOKU_NAV = VI
FORCE_LAYOUT = split_3x6_3

OLED_ENABLE = yes
OLED_DRIVER = SSD1306

WPM_ENABLE = yes