#pragma once

#define NO_ACTION_MACRO
#define NO_ACTION_FUNCTION

#ifndef NO_DEBUG
#define NO_DEBUG
#endif // !NO_DEBUG
#if !defined(NO_PRINT) && !defined(CONSOLE_ENABLE)
#define NO_PRINT
#endif // !NO_PRINT

#ifdef RGBLIGHT_ENABLE
    // #define RGBLIGHT_EFFECT_ALTERNATING
    #define RGBLIGHT_EFFECT_BREATHING
    // #define RGBLIGHT_EFFECT_CHRISTMAS
    // #define RGBLIGHT_EFFECT_KNIGHT
    // #define RGBLIGHT_EFFECT_RAINBOW_MOOD
    // #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
    // #define RGBLIGHT_EFFECT_RGB_TEST
    // #define RGBLIGHT_EFFECT_SNAKE
    // #define RGBLIGHT_EFFECT_STATIC_GRADIENT
    // #define RGBLIGHT_EFFECT_TWINKLE
    // #define RGBLIGHT_LIMIT_VAL 120
    // #define RGBLIGHT_HUE_STEP 10
    // #define RGBLIGHT_SAT_STEP 17
    // #define RGBLIGHT_VAL_STEP 17
    #define RGBLIGHT_DEFAULT_MODE RGBLIGHT_MODE_BREATHING + 1
    #define RGBLIGHT_DEFAULT_HUE 230
    #define RGBLIGHT_DEFAULT_SAT 255
    #define RGBLIGHT_DEFAULT_VAL 255
#endif

#define OLED_TIMEOUT 120000
#define OLED_BRIGHTNESS 120